apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-pods
  labels:
    app: javaapp
    env: dev
  namespace: devnamespace
  annotations: 
    myecrimage: 052076341917.dkr.ecr.us-west-2.amazonaws.com/dev/nginx
spec:
  minReadySeconds: 6
  replicas: 3
  selector:
    matchExpressions:
      - key: web
        operator: In
        values:
          - javaapp
      - key: env
        operator: NotIn
        values:
          - dev
      - key: fortend
        operator: Exists
    strategy:
      type: Rollingupdate
      rollingupdate:
        maxsurge: 1
        maxUnavailable: 1
    templte:
      metadata:
        name: podlevellabels
        labels:
          web: javaapp
          env: prod
          frontend: web
      spec:
        containers:
           - name: javaapp
             image: sravanthi2003/mycssimages:electric
             ports:
               - name: javaapp-ports
                 containerport: 80
                 protocol: TCP
             resources:
                     # requests:
                      #  cpu: 100Mm
                      #  memory: 64Mi    
                   limits:
                     cpu: 500m
                     memory: 256Mi

             startupprobe:
               httpGet:
                 path: "/sravanthi"
                 port: 80
             livenessprobe:
               tcpsocket:
                 port: 80
             readinessprobe:
               exec:
                 command:
                   - echo hi
                   - touch sravanthifile
             resources:
               request:
                 cpu: 10M
                 memory: 50Mi
               limits:
                 cpu: 50M
                 memory: 100Mi       


                  