apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-java
  labels:
    app: java-app
    env: prod
  namespace: dev
  annotations: 
    myecrimage: 052076341917.dkr.ecr.us-west-2.amazonaws.com/dev/devops
spec:
  minReadySeconds: 6
  replicas: 3
  selector:
    matchLabels:
      app: spc-java
  template:
    metadata:
      name: javapod
      labels:
        app: spc-java
    spec:
      containers:
        - name: java-pod
          image: 052076341917.dkr.ecr.us-west-2.amazonaws.com/dev/devops:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            tcpSocket: 
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "400m"
              memory: "2500Mi"
            limits:
              cpu: "1800m"
              memory: "7500Mi"