apiVersion: v1
kind: Service
metadata:
  name: myservicefile
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - port: 80
      targetport: 8080
      protocol: TCP